### PR TITLE
Parse Schnorr Pub Key & Implement TaprootSigVerifierImpl::new

### PR DESCRIPTION
**Pull request by supreme2580**
- [ ] issue #
- [ ] follows contribution [guide](https://github.com/keep-starknet-strange/shinigami/blob/main/CONTRIBUTING.md)
- [ ] code change includes tests

1. parse_schnorr_pub_key : uses the reference from btcd https://github.com/btcsuite/btcd/blob/master/btcec/schnorr/pubkey.go#L23
2. TaprootSigVerifierImpl::new: uses the reference from btcd https://github.com/btcsuite/btcd/blob/24eb815168f49dea84767817717a11bd7928eb23/txscript/sigvalidate.go#L313

### CODE REVIEW

**Comment by Jeanmichel7** [comment]
It would be wise to make your PR against #225 

or merge the PR feat:Taproot into main before? @b-j-roberts

**Comment by supreme2580** [comment]
@Jeanmichel7 do you mean I should pull from feat:Taproot into my own branch?

**Comment by Jeanmichel7** [comment]
> @Jeanmichel7 do you mean I should pull from feat:Taproot into my own branch?

No, instead, make the pull request from your branch to the feat/taproot branch, since TaprootSigVerifier already has the structures.

**Comment by supreme2580** [comment]
Ohhh I see... thanks

**Pull request closed without merging**
