### PR TITLE
[FEAT] implement p2pkh

### PR DESCRIPTION
**Pull request by prasincs**
- [ ] issue #179 
- [ ] follows contribution [guide](https://github.com/keep-starknet-strange/shinigami/blob/main/CONTRIBUTING.md)
- [ ] code change includes tests

I'm trying to do a few naive things first to make sure I understand where the code is right now. I'm trying to replicate some existing tests and it seems to be failing on CHECKSIG and it's unclear if it's some test setup diff or I'm missing something because `test_checksig_valid` seems to work.

### CODE REVIEW

**Comment by j1mbo64** [comment]
Hi @prasincs , I think it's because `OP_CHECKSIG` use the whole transaction to generate signature. You use `mock_transaction` which mock the transaction according to the signature in `test_checksig_valid`.
You can try first to make a `Transaction` who match the desired.
Maybe you can write down the txid you are trying to simulate ?

**Comment by prasincs** [comment]
> Hi @prasincs , I think it's because `OP_CHECKSIG` use the whole transaction to generate signature. You use `mock_transaction` which mock the transaction according to the signature in `test_checksig_valid`. You can try first to make a `Transaction` who match the desired. Maybe you can write down the txid you are trying to simulate ?

I wasn't picking a specific transaction at the time, I was merely trying to pattern match some existing tests to get more familiar with the code. @b-j-roberts pointed me to the right direction. I'm now trying to replicate the first p2pkh tx https://learnmeabitcoin.com/explorer/tx/6f7cf9580f1c2dfb3c4d5d043cdbb128c640e3f20161245aa7372e9666168516#output-0
it's failing on verifying signature, which seems appropriate. Is this verification the missing part?

**Comment by prasincs** [comment]
I think I've noticed the problem.. it seems it's picking up a OP_IF opcode when the original tx doesn't have it 
```
testing shinigami ...
running 1 test
version: 1
transaction_inputs: 2
transaction_outputs: 1
locktime: 0
opcode: 73
opcode: 65
opcode: 172
pk_bytes: 0x04c9560dc538db21476083a5c65a34c7cc219960b1e6f27a87571cd91edfd00dac16dca4b4a7c4ab536f85bc263b3035b762c5576dc6772492b8fb54af23abff6d
full_sig_bytes: 0x3046022100e26d9ff76a07d68369e5782be3f8532d25ecc8add58ee256da6c550b52e8006b022100b4431f5a9a4dcb51cbdcaae935218c0ae4cfc8aa903fe4e5bac4c208290b7d5d01
sig_hash: 97550797732684370436863463553063991333112530509625559142874374105107372342264
r: 102416394157821341409626815012185012746113383284919326646621612654242520629355
s: 81534907895110147809868568149188261236117780672106355691852807290680796478813
top_stack: 
Error: 34304024605757925039519833781264315913130327289331821709226243173
test shinigami::tests::test_transactions::test_p2pkh_transaction ... fail (gas usage est.: 110685388)
failures:
   shinigami::tests::test_transactions::test_p2pkh_transaction - Panicked with "Transaction validation failed".

Error: test result: FAILED. 0 passed; 1 failed; 0 ignored
```
note that it shows 73 followed by 65 whereas the original inoput only has
```
OP_PUSHBYTES_73
3046022100e26d9ff76a07d68369e5782be3f8532d25ecc8add58ee256da6c550b52e8006b022100b4431f5a9a4dcb51cbdcaae935218c0ae4cfc8aa903fe4e5bac4c208290b7d5d01
```

**Comment by prasincs** [comment]
I haven't had much time to look into this but I'd suspected something was wrong with signature validation. So I compared the values from the [tx that spent the first P2PKH tx](https://learnmeabitcoin.com/explorer/tx/12e753ef5cc30925a6eee2c457aa7f53022443ca013ea81882a6b59b69e342a6) and the intermediate values for message and while the values from test_validate_transaction pass, what I have with the P2PKH doesn't. I've pushed it over here if you want to check and run for yourself https://gist.github.com/prasincs/3c133f3fc75931c1f6c4408a6231ae54

**Review by b-j-roberts — APPROVED** [review]

**Comment by b-j-roberts** [comment]
It seems the test was failing due to a bug mentioned and fixed here. https://github.com/keep-starknet-strange/shinigami/pull/209#discussion_r1762318707

Thank you for diving into this, was tricky to find the bug.

**Pull request merged**
