### PR TITLE
[feat] Implement OP_SUB opcode

### PR DESCRIPTION
**Pull request by TAdev0**
- [x] issue #11 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/shinigami/blob/main/CONTRIBUTING.md)
- [x] code change includes tests

Hi @b-j-roberts 

I also added `OP_2` opcode for testing.

I have 2 questions:

- bitcoin wiki says arithmetic operations operates on `i32` not `i64`, is it normal that we use `i64`?
https://en.bitcoin.it/wiki/Script

wiki says : "Note: Arithmetic inputs are limited to signed 32-bit integers, but may overflow their output."

this is why I tested the `OP_SUB` for 
- `1 - 1`
- `2 - 1`
- `1 - 2`

in the last case, i guess an overflow is supposed to happen and return `-1` , currently represented as a `i64` 
But as you can see in test, i get an unwrap error, related to the `assert_eq!` usage on the last line. is it an issue with the macro? but it should work and print the result right?

when i print the ByteArray that will be added to the `ScriptStack` , i get this : 

```
    fn push_int(ref self: ScriptStack, value: i64) {
        let mut bytes = "";
        bytes.append_word(value.into(), 8);
        println!("{}", bytes);
        self.push_byte_array(bytes);
    }
```

```
[DEBUG] 0x46a6158a16a947e5916b2a2ca68501a45e93d7110e81aa2d6438b1c57c879a3
[DEBUG] 0x0 ('')
[DEBUG] 0x800000000000010ffffffffffffffffffffffffffffffffffffffffffffff0b
[DEBUG] 0x9 ('  ')
```

### CODE REVIEW

**Comment by TAdev0** [comment]
@b-j-roberts thanks, now I understand why we use i64

It seems indeed this function will be required

**Comment by b-j-roberts** [comment]
> It seems indeed this function will be required

Would you be interested in implementing that function and making any other required changes to get this working? If not, I'll try and get someone on it asap

**Comment by TAdev0** [comment]
Yeah I can work on it

**Comment by TAdev0** [comment]
@b-j-roberts  should we merge this or do you want me to implement it in this PR?

**Comment by TAdev0** [comment]
@b-j-roberts  just implemented the `Bytes` function. Thus, we can remove the `append_word` method from ByteArray corelib. 

Needed changes in tests because the formatting of the stack is now different, doesnt appear with 8 elements all the time, just like the Go comment here:

```
// Example encodings:
//
//	   127 -> [0x7f]
//	  -127 -> [0xff]
//	   128 -> [0x80 0x00]
//	  -128 -> [0x80 0x80]
//	   129 -> [0x81 0x00]
```

**Pull request merged**
