### PR TITLE
fix: resolves first failing bitcoin-core test

### LINKED ISSUE #247: [bug] Remaining bitcoin-core test fixes
There are a lot of bitcoin-core tests that are still failing. I created this [file with all the failing tests](https://github.com/keep-starknet-strange/shinigami/blob/main/tests/script_tests_failing.json).

The file contains all the failing tests from [this file in bitcoin-core](https://github.com/bitcoin/bitcoin/blob/ab0b5706b254ed914f94b41940a946d84ac8dd6d/src/test/data/script_tests.json#L2).

I threw together [this bash script](https://github.com/keep-starknet-strange/shinigami/blob/main/tests/run-failing-core-tests.sh), which allows you to run all the failing tests.

It will go through them one by one, and print something like this for each failed test : 
```
  ScriptSig: '0x27 0x3024021077777777777777777777777777777777020a7777777777777777777777777777777701' -- ScriptPubKey: '0 CHECKSIG NOT' -- Flags: '' -- Expected: OK
  Expected : OK -- Result   : PANIC
  FAIL
scarb cairo-run --package shinigami_cmds '[[85638222473728638769160410210893464261263086061422684165462972715402475319,97557673223841770041305211021412912560163447137005097938746121282641147703],5288612062596008609236648564283419927782315402045370417,23,[],976111785041138328458856412106580,14,[],0,0]'
     Running shinigami_cmds
Running Bitcoin Script with ScriptSig: '0x27 0x3024021077777777777777777777777777777777020a7777777777777777777777777777777701', ScriptPubKey: '0 CHECKSIG NOT' and Flags: ''
Run panicked with [1637570914057682275393755530660268060279989363 ('Index out of bounds'), ].
```

showing the script that executed, the expected result and the result. The following lines give the scarb command needed to run the failing test manually. Most of the tests have a small bit of info inside the `script_tests_failing.json` file that explains what it is trying to test, which is usually a good hint for where to look.

The task would be to go through these and fix them. Thank you!

Using btcd in general is very useful for seeing bitcoin spec/code to understand how things may differ in our implementation, since our design is heavily inspired by the work there. But in particular [this function will be super useful](https://github.com/btcsuite/btcd/blob/2b53ed198955ac40fe5b3ce4a854e9f5bfa68258/txscript/reference_test.go#L211) in seeing how they map errors to results from these bitcoin-core tests.

### PR DESCRIPTION
**Pull request by SoarinSkySagar**
- [x] resolves #247 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/shinigami/blob/main/CONTRIBUTING.md)
- [ ] ~code change includes tests~

Earlier, the first test in the `.tests/script_tests_failing.json` was failing due to it receiving the wrong type of error message. the expected error was `SCRIPT_ERR_SIG_DER` but it got `SIG_HASHTYPE` error instead. This PR fixes that issue.

### CODE REVIEW

**Comment by SoarinSkySagar** [comment]
Hi @b-j-roberts, please review the PR

**Comment by bloomingpeach** [comment]
Have you tried running the core test script and make sure no new tests are failing? @SoarinSkySagar

**Comment by bloomingpeach** [comment]
you should run `bash ./tests/run-core-tests.sh` to update the `script_tests_failing.json` and `script_tests_passing.json`

> > Have you tried running the core test script and make sure no new tests are failing? @SoarinSkySagar
> 
> Yes, I made sure of that @bloomingpeach

**Comment by SoarinSkySagar** [comment]
done! @bloomingpeach

**Comment by SoarinSkySagar** [comment]
> you should run `bash ./tests/run-core-tests.sh` to update the `script_tests_failing.json` and `script_tests_passing.json`
> 

done @bloomingpeach!

**Comment by bloomingpeach** [comment]
Nice! You have fixed ten more tests, really good job!

**Comment by bloomingpeach** [comment]
LGTM, waiting for @b-j-roberts' review

**Comment by b-j-roberts** [comment]
@bloomingpeach Thank you for helping review!

**Review by b-j-roberts — APPROVED** [review]
Lets go, great work! Only a handful of tests remaining!

**Pull request merged**
