### PR TITLE
[feat]Implementation of OP_DATA_1 opcode

### PR DESCRIPTION
**Pull request by Shoetan**
- [ ] issue #
- [ ] follows contribution [guide](https://github.com/keep-starknet-strange/shinigami/blob/main/CONTRIBUTING.md)
- [ ] code change includes tests

### CODE REVIEW

**Review by b-j-roberts — CHANGES_REQUESTED** [review]
This implementation is doing something more similar to opcodeN, like `OP_1`, instead of opcodePushData here https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L796.
You can check this out for more details: https://wiki.bitcoinsv.io/index.php/Pushdata_Opcodes#:~:text=OP_PUSHDATA1%20(76%20or%200x4C),-OP_PUSHDATA1%20takes%20the&text=It%20can%20be%20used%20to,data%20item%20on%20the%20stack.

You will need to use the script and opcode_idx from the engine to figure out where to get the byte data from, I believe.

**Comment by b-j-roberts** [comment]
Hey @Shoetan , I had implemented this opcode in another PR due to changes needed in the engine and compiler : https://github.com/keep-starknet-strange/shinigami/blob/6e686aa67cb63ae7b351a3697f5455a30eb76dc0/src/opcodes/constants.cairo#L10

Would you be interested in implementing the remaining `OP_DATA_X` opcodes, `OP_DATA_7` - `OP_DATA_75`?

**Comment by Shoetan** [comment]
@b-j-roberts  yes I'll love to give a try. Thank you.

**Comment by b-j-roberts** [comment]
> @b-j-roberts yes I'll love to give a try. Thank you.

Awesome, would you like to create the issue or I can?

**Comment by Shoetan** [comment]
I would love you to create the issue. I am learning best practices from you on how to maintain projects 🙂

**Pull request closed without merging**
