### PR TITLE
fix: fix opchecksig bug

### LINKED ISSUE #211: [bug] [bitcoin-core test] ScriptSig: '0x27 0x3024021077777777777777777777777777777777020a7777777777777777777777777777777701' -- ScriptPubKey: '0 CHECKSIG NOT'
### Issue

The following bitcoin-core test is failing to give the correct result :
```
ScriptSig: '0x27 0x3024021077777777777777777777777777777777020a7777777777777777777777777777777701' -- ScriptPubKey: '0 CHECKSIG NOT'
```

This code should be passing, but is panicking when executing.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[85638222473728638769160410210893464261263086061422684165462972715402475319,97557673223841770041305211021412912560163447137005097938746121282641147703],5288612062596008609236648564283419927782315402045370417,23,[],976111785041138328458856412106580,14,[],0,0]'
```

This comment might help some with how to debug : https://github.com/keep-starknet-strange/shinigami/pull/192#issuecomment-2322981566

### LINKED ISSUE #212: [bug] [bitcoin-core test] ScriptSig: '0x27 0x302402107777777777777777777777777777777702108777777777777777777777777777777701' -- ScriptPubKey: '0 CHECKSIG NOT'
### Issue

The following bitcoin-core test is failing to give the correct result :
```
ScriptSig: '0x27 0x302402107777777777777777777777777777777702108777777777777777777777777777777701' -- ScriptPubKey: '0 CHECKSIG NOT'
```

This code should be passing, but is panicking while executing.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[85638222473728638769160410210893464261263086061422684165462972715402475319,97557673223841770041305211021412912560163447201069703897584165137845532471],5288612062596008609236648564283419927782315402045370417,23,[],976111785041138328458856412106580,14,[],0,0]'
```

This comment might help some with how to debug : https://github.com/keep-starknet-strange/shinigami/pull/192#issuecomment-2322981566

### PR DESCRIPTION
**Pull request by bloomingpeach**
- [x] fixes #211 
- [x] fixes #212 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/shinigami/blob/main/CONTRIBUTING.md)
- [ ] code change includes tests

image

image

### CODE REVIEW

**Comment by b-j-roberts** [comment]
Hey, were you able to track down which line was giving the index out-of-bounds error? I'm curious where it was failing

**Comment by bloomingpeach** [comment]
it fails here: https://github.com/keep-starknet-strange/shinigami/blob/main/packages/engine/src/signature/signature.cairo#L298

By the way I think it is not supposed to go that far with an empty pubkey, https://github.com/keep-starknet-strange/shinigami/blob/main/packages/engine/src/signature/signature.cairo#L252 I think we should at least have a check for empty pubkey before or inside this function.

**Comment by b-j-roberts** [comment]
I see, thanks for the info! I think how you did it is a good solution. 

However, I think we should also add a check [here](https://github.com/keep-starknet-strange/shinigami/blob/13f6cf41c6ea1d3c229a2f10ce2ddb0a4626c6cc/packages/engine/src/signature/signature.cairo#L296) for if the `pk_bytes.len != 65` and return an error, since uncompressed pub keys should always be of length 65 I think.

Would need to make `parse_pub_key` return an error too.

**Comment by bloomingpeach** [comment]
Would you like me to include the check in this PR or should it be in another PR? @b-j-roberts

**Comment by b-j-roberts** [comment]
> Would you like me to include the check in this PR or should it be in another PR? @b-j-roberts

In this PR if you can, thanks

**Comment by bloomingpeach** [comment]
@b-j-roberts please review sir

**Review by b-j-roberts — APPROVED** [review]
Sorry for taking forever to get to this, thank you! And great work as always.

**Pull request merged**
